import React, { useEffect } from "react";
import { useLocation } from "react-router-dom";

const FAQ = () => {
  const location = useLocation();

  useEffect(() => {
    const searchParams = new URLSearchParams(location.search);
    const section = searchParams.get("section");

    if (section === "credits") {
      const creditsElement = document.getElementById("credits");
      if (creditsElement) {
        creditsElement.scrollIntoView({ behavior: "smooth" });
      }
    }
  }, [location]);

  return (
    <div className="pt-20 m-10 md:mx-60">
      <h1 className="text-3xl font-semibold text-center">
        <span class="text-3xl text-orange-500">Oscr AI </span>Frequently Asked
        Questions
      </h1>
      <ol class="list-decimal">
        <li class="font-semibold">What is Oscr AI?</li>
        <p class="m-1 leading-7">
          Oscr AI is a powerful tool designed to help marketers create
          personalized and engaging content by leveraging their own data or
          research. Our AI-driven platform assists in generating
          context-specific marketing materials, making it easier to connect with
          your audience.
        </p>

        <li class="font-semibold">How does Oscr AI work?</li>
        <p class="m-1 leading-7">
          Oscr AI uses advanced AI algorithms to analyze your data and generate
          tailored content for your marketing needs. Simply input your source
          data into our platform, and Oscr AI will create contextually relevant
          content that resonates with your target audience.
        </p>
        <li class="font-semibold">
          What types of content can Oscr AI generate?
        </li>
        <p class="m-1 leading-7">
          Oscr AI can help create a wide range of marketing materials in their
          social tools, including blog posts, social media content, research
          reports, and more. The content is customized based on the specific
          needs and data provided by your business.
        </p>
        <li class="font-semibold">How do I get started with Oscr AI?</li>
        <p class="m-1 leading-7">
          Getting started with Oscr AI is easy. Sign up for an account on our
          website, pick a task flow, upload your data, and start generating
          tailored marketing content. Alternatively, you can research with our
          research tool, and repurpose the results to downstream tasks. Our
          user-friendly interface will guide you through the process
          step-by-step.
        </p>
        <li class="font-semibold">Is my data secure with Oscr AI?</li>
        <p class="m-1 leading-7">
          Absolutely. We take data security very seriously at Oscr AI. All data
          uploaded to our platform is encrypted and stored securely. We adhere
          to strict privacy policies to ensure your data is protected at all
          times.
        </p>
        <li class="font-semibold">
          Can Oscr AI integrate with other marketing tools?
        </li>
        <p class="m-1 leading-7">
          Coming soon! Oscr AI is designed to integrate seamlessly with popular
          marketing tools and platforms. This will allow you to easily
          incorporate the content generated by Oscr AI into your existing
          marketing workflows.
        </p>
        <li class="font-semibold">
          How accurate is the content generated by Oscr AI?
        </li>
        <p class="m-1 leading-7">
          Oscr AI uses state-of-the-art AI technology to ensure the content it
          generates is highly accurate and relevant. The research tool will
          fetch reference links to support generated output. However, we
          recommend reviewing and customizing the content as one last step to
          ensure it perfectly aligns with your brand's voice and objectives.
        </p>
        <li class="font-semibold">
          What kind of data do I need to provide to Oscr AI?
        </li>
        <p class="m-1 leading-7">
          To get the best results from Oscr AI, provide data that is relevant to
          your marketing goals, such as your product and services, context of
          your stories and researches. This can include customer demographics,
          previous marketing campaigns, sales data, and any other information
          that can help tailor the content to your needs.
        </p>
        <li class="font-semibold">How much does Oscr AI cost?</li>
        <p class="m-1 leading-7">
          Oscr AI offers various pricing plans to suit different business needs.
          For detailed information on our pricing, please visit our pricing page
          on the website or contact our support team:
          <a
            href="mailto:support@oscr.tech"
            class="text-orange-500"
            target="_blank"
          >
            support@oscr.tech
          </a>
          .
        </p>
        <li class="font-semibold">
          How can I get support if I encounter issues?
        </li>
        <p class="m-1 leading-7">
          Our dedicated support team is here to help you with any issues or
          <span id="credits"></span>
          questions you may have. You can reach out to us via the contact form
          on our website, or through our support email:
          <a
            href="mailto:support@oscr.tech"
            class="text-orange-500"
            target="_blank"
          >
            support@oscr.tech
          </a>
          . We also offer a comprehensive help center with FAQs, tutorials, and
          guides.
        </p>

        <li class="font-semibold">
          How are credits counted towards end results?
        </li>
        <p class="m-1 leading-7">
          Each workflow uses a different amount of credits. We provide a counter
          on the left-hand side menu bar to help you track your credit usage.
          The credits required for each task vary, but here is a breakdown:
        </p>
        <div class="overflow-x-auto">
          <table class="min-w-full bg-white border border-gray-200">
            <thead class="bg-gray-200">
              <tr>
                <th class="py-2 px-4 border-b border-gray-300 text-left">
                  Task
                </th>
                <th class="py-2 px-4 border-b border-gray-300 text-left">
                  Credits Needed
                </th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td class="py-2 px-4 border-b border-gray-300">
                  Blog post generation
                </td>
                <td class="py-2 px-4 border-b border-gray-300">15</td>
              </tr>
              <tr class="bg-gray-50">
                <td class="py-2 px-4 border-b border-gray-300">
                  Research Report
                </td>
                <td class="py-2 px-4 border-b border-gray-300">15</td>
              </tr>
              <tr>
                <td class="py-2 px-4 border-b border-gray-300">
                  Youtube video transcript
                </td>
                <td class="py-2 px-4 border-b border-gray-300">10</td>
              </tr>
              <tr class="bg-gray-50">
                <td class="py-2 px-4 border-b border-gray-300">
                  Youtube video summary
                </td>
                <td class="py-2 px-4 border-b border-gray-300">10</td>
              </tr>
              <tr>
                <td class="py-2 px-4 border-b border-gray-300">
                  Youtube video translation
                </td>
                <td class="py-2 px-4 border-b border-gray-300">10</td>
              </tr>
              <tr class="bg-gray-50">
                <td class="py-2 px-4 border-b border-gray-300">
                  Linkedin post generation
                </td>
                <td class="py-2 px-4 border-b border-gray-300">10</td>
              </tr>
              <tr>
                <td class="py-2 px-4 border-b border-gray-300">Discovery</td>
                <td class="py-2 px-4 border-b border-gray-300">10</td>
              </tr>
            </tbody>
          </table>
        </div>
        <li class="font-semibold">What happens if I run out of credits?</li>
        <p class="m-1 leading-7">
          Your workflow credits will reset at the beginning of each month. If
          you need more credits before then, additional credit purchasing
          options will be available soon. Alternatively, you can upgrade to our
          Pro or Super-Star plans for more credits and enhanced features.
        </p>
        <li class="font-semibold">
          What makes Oscr AI different from other content generation tools?
        </li>
        <p class="m-1 leading-7">
          Oscr AI stands out due to its ability to generate highly contextual
          and personalized content based on your own data. Our advanced AI
          algorithms ensure that the content is not only relevant but also
          engaging and tailored to your target audience.
        </p>
        <li class="font-semibold">
          Is there a free trial available for Oscr AI?
        </li>
        <p class="m-1 leading-7">
          Yes, we offer a free trial so you can experience the capabilities of
          Oscr AI before committing to a subscription. Sign up on our website to
          start your free trial today.
        </p>
        <li class="font-semibold">How often is the AI updated?</li>
        <p class="m-1 leading-7">
          Our AI is continuously updated to incorporate the latest advancements
          in technology and to improve its content generation capabilities. We
          strive to ensure that Oscr AI remains at the forefront of AI-driven
          marketing solutions.
        </p>
        <li class="font-semibold">Can Oscr AI help with SEO?</li>
        <p class="m-1 leading-7">
          Yes, Oscr AI can assist in creating SEO-friendly content. By analyzing
          your data and relevant keywords, Oscr AI generates content that is
          optimized for search engines, helping to improve your online
          visibility.
        </p>
      </ol>
    </div>
  );
};

export default FAQ;
